apiVersion: apps/v1
kind: Deployment
metadata:
  name: user10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user10
  template:
    metadata:
      labels:
        app: user10
    spec:
      containers:
        - name: user10-server
          image: ghcr.io/lovenarins/microservice-devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user10-service
  labels:
    app: user10-service
spec:
  selector:
    app: user10
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
