apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-devops
  template:
    metadata:
      labels:
        app: microservice-devops
    spec:
      containers:
        - name: microservice-devops-server
          image: ghcr.io/lovenarins/microservice-devops
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-devops-service
  labels:
    app: microservice-devops-service
spec:
  selector:
    app: microservice-devops
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
